const config = {
  "name": "n",
  "aliases": ["nv2"],
  "description": "",
  "usage": "",
  "cooldown": 3,
  "permissions": [2],
  "credits": "WaifuCat",
  "extra": {}
};

const list = [
  "con đĩ ngu bị cha chửi k ngốc đầu lên đc🤣",
  "sao m cay t vậy tr🤣🤖",
  "thg óc đú m sủa lẹ đê",
  "cay đến nỗi phải bỏ cha vô hạn chế à:))?",
  "cay cha k con eii",
  "sủa lẹ đi🤣🤣",
  "thg culi ô xin mà đòi đú à",
  "lên bem cha đê🤣🤔",
  "sủa đê🤣",
  "mẹ m bị t đụ kìa🤤🤣",
  "cay k con",
  "mày hài v tr",
  "thg ngu đú bị cha chửi cho ko ngốc đầu lên đc🤣🤣",
  "lần sau gặp cha lehuuphat thì xin tha đi🤣",
  "lên chửi nhau với cha phát:))?🤣",
  "cha lên giết cha mẹ m nè con🤣",
  "mày sợ à con 🐕",
  "thg bất hiếu ám sát cha mẹ",
  "mày bại t rõ mà",
  "còn cố gì nx tr🤣🙃",
  "thg ngu loạn luân với mẹ mà còn chối🤤🤣",
  "t cân cả dòng họ m mà:))",
  "Mày đang mếu vì bị cha chửi đúng ko🤣",
  "bú cứt cha đi cha tha cho m nè con🤣",
  "thg bê đê bị cha chửi cay phải tự tử",
  "bớt sủa dơ đi nha e eiii",
  "tao đã cho m câm chưa hả",
  "thg ngu đòi bem cha và cái kết...🤣",
  "mày cảm thấy bất lực khi bị t bem đúng k",
  "thg ngu đú war kiểu🤣",
  "mới có xíu m đã bại t mẹ r",
  "yếu rồi còn sĩ",
  "m còn gì khác để làm tao cay không",
  "hay là chỉ biết ăn hôi🤣",
  "đúng là thg tật mồ côi🤣",
  "Mù ngôn ngữ",
  "sài adr 2m đòi khè ai v tr",
  "thg tật bẩm sinh🤣",
  "đáy của xã hội",
  "bốc cứt ăn qua ngày🤣",
  "tưởng mình hay",
  "mà trong khi mình ngu hơn 1 con dog",
  "mày bại tao all sàn mxh với real mà",
  "còn cãi đc k🤣",
  "cãi to lên🤣🤤",
  "xem m trụ đc bao lâu:))",
  "thg ngu ko có não phải gắn não bò thay thế🤣🤣",
  "cạn bã của XH mà tưởng mình hay🤣💨",
  "đúng dân va 2023 có khác",
  "sủa câu nào làm t cười tới đó",
  "con thí nhai đi nhai lại ngôn v🤣",
  "m có trình k v thg bẻm?",
  "thg đú lgbt ớt cmnr🤣",
  "cầu cứu ae mày đi",
  "hay là phế quá nên bị ae m ruồng bỏ🤣",
  "đúng thg bẻm ngu còn ảo🤣",
  "cạn ngôn ngữ r à?😃",
  "mới gõ có tí đã mệt r à",
  "cố đi con chó thất học🥲",
  "sủa đi",
"cố lên con",
"sồn hăng lên em",
"sao m yếu v ",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em=))",
"cố gắng tí con chó dốt=))",
"k đc à",
"con chó ngu cố đê",
"sao m câm kìa",
"gà j",
"mày sợ anh à =))",
"m gà mà",
"mày ngu rõ mà",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ đi con dốt",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi con đĩ",
"cố lên con chó ngu",
"=)) cay tao à con đĩ",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố lên chó dốt",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"sợ tao à con chó đần",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới 5p đã câm r",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"mày óc à con chó bẻm=))",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận à con đĩ",
"thg cặc giết cha mắng mẹ",
"sủa mạnh eii",
  "Lũ đú ấm ức cha mày rõ mà😗❗",
  "Sao rồi ổn lòi lìa hả 🤔",
  "Cha mày đấng mxh mà lũ ngu🤣",
  "Cay cha mày lắm r phải kh",
  "Đái ra máu r kìa cn ngu ơi🤣",
  "Cưng xạo lồn bịa chuyện là hay😗",
  "Chứ trình mày làm gì có tuổi ăn anh🤣",
  "Cưng hăng hái 1 cách bất thường à🤣",
  "Cay cú anh trong lòng mà không làm đc gì🤔🌶", 
  "Cay đỏ bướm rồi à cn ngu🌶❗",
  "Thk cặc cay anh đỏ dái mẹ r🌶❗🤪",
  "Khi nào cs trình v cn ôn thú",
  "Mặt mày như cn quái thai từ trong bào thai v🤪",
  "Ê con suy tàn đạo đức🤪",
  "Nhân cách thối nát đáy của tạp chủng 🤣",
  "Cái con không có địa vị bằng 1 cn súc vật nữa🤪🤣",
  "Cha mày gõ cho mày nguyên 1 tràn lan đại hải🤣",
  "Gõ cho mày tá hỏa tâm tinh🤪",
  "Gõ cho mày siêu thoát quá thế giới bên kia🤣",
  "Con đỉ bị cha hành hạ🤪",
  "Cn tinh tinh mặt cặc❗",
  "Cn thú mặt người",
  "Cn khỉ mặt nhân loại🐵❗",
  "Cn tạp nham cay anh🌶❗",
  "Khóc r à em🤣❗",
  "Bất ổn r à🤣",
  "Mếu máo mẹ mày r🤣",
  "Sao rồi em gái🤣",
  "Mày bị cha cho cay cú mà🌶🤣",
  "Về méc mẹ rồi à🤣",
  "Sao không hăng nx đi🤣",
  "Gõ yếu vậy à🤣",
  "Gõ sồn máu lồn mày lên",
  "Hăng hái lên cha xem🤣",
  "Cay cú nên hóa rồ rồi à🤣",
  "Mới gõ tí đã đuối rồi🤣",
  "Bị anh cho ngậm đống hành trong mõm r🤣🤣",
  "Gõ sồn sồn lên xôm lên xem nào🤣",
  "Bất ổn cmnr🤣",
  "Não bị cha mày cho tàn phế r à🤣",
  "Ê sao cn thú nhai ngôn r🤣",
  "Sức cùng lực kiệt r à🤣",
  "Ê cay đái kh còn giọt máu r à🤣",
  "Cha mày chuyên trị lũ đú mà🤣",
  "Cưng sao v hả🤣",
  "Không hăng như lúc đầu nữa hả🤣",
  "Eo ôi:>🤪",
  "Còn sống kh v😗",
  "Mày bị cha hành mà:3",
  "Cha cấm mày bịa chuyện nha🤔",
  "Cha quin mà cn thú êy🤪",
  "Hóng quin đc cha lắm hỏ🤪",
  "Ê cn quái thú🤪",
  "Mày là cn quái thú giữa rừng xanh mà🤪",
  "Mày tưởng mày đang đóng vai ng đẹp và quái vật hả🤪",
  "Mày tưởng mày đang đóng vai ng đẹp và quái vật hả🤪",
  "Thoát ra khỏi cái mộng tưởng đó đi nhóc🤪",
  "Sao bị cha chửi mà tha hóa lun r🤪",
  "Sống phèn quá v cn thú đú êy😳",
  "Mếu cha mẹ r🤪",
  "Cay cú mẹ r🌶❗",
  "Lgbt bày binh bố trận dồn cha hả🤪❗",
  "Dồn ngu mà cũng đòi dồn❗🦋",
  "Nhìn lũ tật cầm cái phím tắt hăng ghê🤣",
  "Cha mày chúa tể trị lũ đú🤪",
  "Cha mày bón cứt dô mõm m nè😏",
  "Ê đỉ ngu🤣",
  "Sao rồi ổn kh",
  "Hay ổn lòi lìa😴😳",
  "Nhìn mặt m là bt không ổn r😳",
  "Cn tinh tinh bị cha đọa đày😁",
  "Bị cha mày đọa đày xuống diêm la địa phủ😗",
  "Để đầu thai chuyển kiếp thành súc vật🤣",
  "Đừng cay cha mà làm liều❗❗",
  "Nhìn bản mặt mày là đủ hiểu cay cỡ nào🌶",
  "Mày đái ra máu r kìa🌶🤣",
  "Nhanh tay lên nào🤣",
  "Nhanh tay múc nc máu lồn cho tk cha mày uống lẹ🤣",
  "Rồi lun cn ôn thú bị anh sỉ nhục mẹ r🤣",
  "Sỉ nhục như cn động vật bậc thấp🤣",
  " ngu si 4 chi phát triển🤪",
  "Tự nhiên cái hăng ngang dị🤣",
  "Hăng ngang làm anh sợ ghê 😱",
  "Hăng lên đc tí r ngủm r à🤪",
  "Đái ra máu xè xè r🤣❗",
  "Ăn năn xám hối r à ❗🤣",
  "Cay quá nên uống nc đái chó cho đỡ cay đi em🤣",
  "Mếu chết đỉ mẹ mày đi",
  "Đầu thai mẹ mày đi cn tạp chủng🤣",
  "Cn ngu xi đần độn dốt nát🤣",
  "Bị cha cho tha hóa thành cchó ngu dốt🤣",
  "Sao mày ngu như 🐮 v",
  "Cay cay cay cha rồi🤣",
  "Ai cho mày cay cha hả🤣",
  "Cay chừa phần người ta với🤣",
  "Cay ht phần thiên hạ là sao dị 🤨",
  "Ê cn thú hoang dã🤣",
  "Cn dị tật bẩm sinh liệt não",
  "Hấp hối mẹ mày rồi à🤨",
  "Cha mày trùm đấng mxh ai làm lại anh đâu😁",
  "Mày khóc rồi à🤣",
  "Con bào thai trong ống nghiệm cũng bt mếu à🤣",
  "Mày sủa như cách cn chó nhà mày sủa đê🤣", 
  "Ê sao cay cú cha mày rồi😳",
  "Ai cho mày cay cha hả😗",
  "Cn tinh tinh đội lót nhân dân hại dân lành🤣",
  "Cạn ngôn r hả cn thú ngu êy",
  "Sao lặp ngôn liên tục v🤣",
  "Gõ dài dòng kh dame thì gõ làm gì🤣",
  "Mày là cn phò trường chinh mà🤣",
  "Cn thú mại dâm bán dâm mà như bán trinh hoa hậu v🤣",
  "Ê cn đỉ phát ngôn xàm bậy🤣",
  "Mày đừng tự vả dô mặt m nữa🤣",
  "Nhìn mày là bt kh ổn r!",
  "Mày bt anh là chuyên trừng trị những thể loại như m kh",
  "Sao mày đú quá v🤣", 
  "Khi nào ht đú hả cn thú ngu",
  "Chắc xog quả này chắc ht đú ha",
  "Ê cn thú ngu ngục bẩm sinh",
  "Mày là cn thú ms đẻ ra đã ngu sẵn r🤣",
  "Ê cn âm binh đầu đường xó chợ🤪",
  "Mày hăng mạnh mẽ lên đê🤪",
  "Sao tự nhiên yếu xìu như xìu cặc v🤣",
  "Mẹ mày bị mày loạn luân đụ rung lồn mà🤣",
  "Cặc chưa mọc lông mà đòi đụ này đụ kia🤣",
  "con chó ngu ngục lên thể hiện trình bị anh sút🤣", 
  "thằng ngu đang cố tỏ ra mình ổn à", 
  "ơ ơ ơ sao em lại hăng ", 
  "dân war 2024 hăng ròi kìa ae", 
  "bị anh chọc cho tê cu à ", 
  "nhìn tk óc dái đú đang đú bot nhìn ngu vậy 🤣", 
  "ơ tk ngu ai treo vậy em ", 
  "tự nhiên treo vậy tk gà bí ngôn", 
  "ai giả bộ sợ cho em nó đỡ quê đê😝", 
  "tk ngu ăn cứt tao mà ra oai à", 
  "sao em đú dữ vậy tỉnh lên đê",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
"mày óc à con",
"tao cho m chạy à",
"con đĩ ngu sủa?",
"mày chạy à con đĩ lồn",
  "con gái mẹ mày chết kìa 😏😏",
  "bắt quả tang con chó chạy bố nè",
  "rồi lun nó méc mẹ à",
  "hkhiet xuất trận eiii",
  "hkhiet bá mà ơ",
  "bịa kìa ae",
  "mày bịa như con gái mẹ mày vậy",
  "rồi luôn con bede sợ rồi",
  "rồi rồi nó phèn kìa",
  "mày sợ rồi hả",
  "quốc thiên win sàn này mà",
  "kkk con bede bị j rồi kìa",
  "trời má ơi nó sợ bố à",
  "sồn miếng đi em ?",
  "sợ lắm pk",
  "mày làm j đc bố dọ",
  "con bede cay dái kiểu :))",
  "con bồ mày bị tao đụ tét lồn mà",
  "con đầu đất này",
  "nhìn nó sồn hài vl ae",
  "mày bede xuất trận à em",
  "con gái mẹ mày cầu xin tao kìa",
  ":))",
  "con bede sồn kìa",
  "sợ j đó",
  "mày bịa anh sợ mày à",
  "con chó bịa vậy",
  "bịa quá ko tốt đâu",
  "hkhiet xuất trận cmnr 😜😜",
  "nhìn con bede sồn kìa",
  "sợ r hả",
  ":))",
  "nó sợ tớ kìa",
  "sồn gái mẹ mày đê",
  "bố bá mà",
  "ơ con bede mày cay mẹ rồi :))",
  "mày k có câu nào khác nữa à",
  "con bede bớt sồn mẹ mày đê",
  "cay j ó",
  "bịa mẹ j ghê vậy",
  "con bede mày làm ko lại anh à",
  "làm ko lại nên mới bịa nè",
  "sồn như cách mày chịch ghệ m đó em",
  "=))",
  "rồi lun nó tức kìa 🤣🤣",
  "mày lỏ dái v",
  "con gái mẹ mày die r kìa",
  "sồn đê",
  "ơ ơ con bede",
  "hăng mẹ mày đê",
  "con bede ăn hiếp bố à",
  "con cay kìa",
  "cay boài mẹ r",
  "nói mày á em",
  ":))",
  "mày sợ tao mà",
  "mày thèm con cu bố mà",
  "ô ô mày tục tĩu bậy 😏",
  "quéo cặc rồi à",
  "m sợ kìa",
  "ê ê tk ngu",
  ":))",
  "con béo m sợ kìa",
  "m ngu thật",
  "rén à",
  "nó rén tao thật r",
  "mày sợ tao òi",
  "m ngu kiàaa",
  "con chó sủa đê",
  "mày ngu vãi",
  ":))",
  "con đĩ mẹ mày",
  "mẹ mày die r à",
  "má ơi nó sồn kìa",
  "con đĩ mẹ m die kìa",
  "mẹ ơi",
  "m sợ kiàaa",
  "con sugar daddy :))",
  "ơ ơ sồn kìa :))",
  "sủa mẹ m đê con bede",
  "m sồn quá dạ",
  "hí hí 🤣",
  "má mày",
  "=))",
  "nhìn nó nch joke vl",
  "m béo vãi",
  "con chó béo v",
  "m béo v",
  "con điên eiii",
  "con gái mẹ mày kìa",
  ":))",
  "con culi sồn dọ",
  "hkhiet win mà 😜",
  "ơ ơ bede",
  "sao mày béo vậy em",
  "ơ ơ",
  "😏😏",
  "con mẹ mày",
  "con đĩ mẹ mày",
  "gái mẹ mày die kìa",
  "mẹ m",
  "ê ê con chó",
  "đĩ mẹ mày",
  "sủa đê",
  "🤣🤣",
  "mẹ m die kìa",
  "bố win mà",
  "trời trời",
  "anh win mà",
  "mày dámm tranh vs anh à",
  "con điên boài",
  "🤣🤣",
  "sủa êyy",
  "m die kìa",
  "má mẹ m",
  ":))",
  "con die bầm",
  "ủa m sợ à",
  "m sợ anh mà",
  "con bede sợ r kìa",
  "j dọ",
  "gái mẹ m 🤣🤣",
  "ô ô",
  "cười mẹ mày à",
  "m sợ kìa",
  "con điên",
  "con chó",
  "🤣🤣",
  "gái má m nè",
  "sồn kìa ơ",
  "hkhiet đấng sàn war mà",
  "bố bá mà",
  "m điên mà",
  "m die kìa",
  "mày sợ kiàa 😜",
  "con tật rách chân à",
  "sồn như cách m die di em",
  "mẹ m",
  "m lbgt r à",
  "sao j",
  "mày câm à",
  "mày câm mẹ rồi",
  "con chó cay anh",
  "con mẹ mày",
  "sồn v em",
  "die mẹ m r à",
  "con chó",
  "🤣🤣",
  "chết kiàa 🤣🤣",
  "kìa kìa",
  "sao sồn dọ",
  "chết kìa",
  "cdm tk não bò",
  "chó ơi",
  "sủa đê",
  "m cay t à em",
  "con chó sợ chạy kida",
  "hăng êiiii",
  "đồ con ngu",
  "con bede seen lén à",
  "a cho m chạy chx",
  "m sợ bố mà",
  "r r nó sợ r",
  "mày cay bố kìa",
  "kkk",
  "m sợ bố mà",
  "cayyy 😜",
  "con chó ngôn kém v",
  "m ngu ngục mà",
  "con bede cay boài rồi kìa",
  "con chó xuất trận êyyy",
  "hkhiet win à",
  "ô hkhiet win mẹ r",
  "m béo m tự ti mà",
  "m bị bọn t đá mà",
  "sao m sợ v",
  "đừng sợ mà",
  "sợ là kém cõi lắm đấy",
  "sao m phèn vậy",
  "m phèn rõ mà",
  "ô con chó cái này :))",
  "con béo sợ à",
  "bố cấm m sợ nha",
  "t cho m sợ chx",
  "m ảo à",
  "con chó ảo win kìa",
  "m béo vcl",
  "rên kinh vl",
  "bại bố à",
  "m bại bố mẹ kìa",
  "con chó bede ",
  "sồn đê em",
  "con chó cay bẻm",
  "r xong chạy r kìa",
  "mày ngu vãi cặc",
  "con chó êyyy",
  "rồi xong nó cay bẻm òi",
  "mẹ m die thảm kìa",
  "con chó ngu vl",
  "r xong nó die r",
  "con mẹ mày ngu vãi 😏",
  "r xong chạy r kìa",
  "con bede sồn đê",
  "mày chạy à",
  ":))",
  "hmm",
  "nó gần hết ngôn rồi à",
  "con mèo hoang hết ngôn kìa",
  "con chó cay boài",
  "con bẻm cay này",
  "rồi xog nó lên xe chạy bẻm mạng rồi",
  "con bot ngu này",
  "mày ngu và thần kinh vãi :))",
  "mày sồn đê em",
  "con chó cực nhọc v",
  "=))",
  "con giết mẹ mắng cha này",
  "ko lmj đc à",
  "hhh:))",
  "con bẻm sợ quéo cặc rồi",
  "mày sợ bố như ma mà",
  "hkhiet bá vl 😏",
  "con bede xưng đấng à",
  "hot ỉa chạy mẹ rồi",
  "con bẻm :))",
  "mày định giết tg à",
  "con chó ngu hiểu sai nghĩa kìa",
  "tg là thời gian mà",
  "ô con chó ngu hiểu sai quê :))",
  "chó này quê v",
  "r r nó cắn kìa",
  "bố bá vl 😏",
  "m sợ bố như sợ đò mà",
  "rồi xong nó chạy rồi",
  "con bẻm cay à",
  "bố cho cay chưa",
  "bố cấm mày cay mà",
  "con lồn dốt nát này",
  "mẹ m béo vl",
  "giảm mỡ đê",
  "con đĩ nhà nghèo",
  "nhìn m sồn trụ vs bot mắt cừi vl :))",
  "con chó m phèn v",
  "m nghèo mà em",
  "m chạy mẹ rồi à",
  "bố chưa cho chạy mà",
  "mẹ ơi nó chạy kìa",
  "ngu v",
  "sồn ê",
  "chửi bố đê",
  "mày nhát v em",
  "bồ m bị chửi k kháng cự bảo vệ à",
  "tk hèn 😏",
  "bố giết cả nhà m mà",
  "con chó tục v",
  "bot j kìa",
  "bịa à",
  "con chó dốt ngu bịa kiểu :))",
  "nhìn m phèn vl",
  "m dốt nát vãi",
  "m ko = 1 gốc tao mà",
  "m sợ bố mún die mà",
  "m đi đầu thai đê con chó êyyy",
  "mẹ m die bẻm r kìa",
  "mày đê cầu cứu đê",
  "gọi ng chửi bố đê",
  "m sợ tao mà",
  "con chó bẻm",
  "bố cấm m sợ tao mà",
  "sao m sợ tao vậy",
  "nó sợ tao à",
  "mẹ m die bầm kìa",
  "rồi xong",
  "nó die r",
  "con chó ngôn phèn",
  "m ngôn bẩn vl",
  "m phèn mà",
  "sủa mẹ m đê",
  "con chó dốt êyyy",
  "m chít mẹ m r",
  "sồn ào mẹ",
  ];

let index = 0;
let isStopped = false;

export function onCall({ message }) {
  const args = message.body.split(" ").slice(1); 
  if (args[0] === "stop") {
    isStopped = true; 
    message.send("🤣🤣👈");
    return;
  }
  
  if (isStopped) {
    isStopped = false;
  }
  
  const sendText = () => {
    message.send(list[index]);
    index = (index + 1) % list.length;
    if (!isStopped) {
      setTimeout(sendText, 2000); 
    }
  };
  sendText();
}

export default {
  config,
  onCall
};
